### ISSUE TITLE
JVN#67001206：『FreeStyleWiki』にクロスサイト・スクリプティングを含む複数の脆弱性

### ISSUE THREAD

**Issue by hangingman** [hangingman/fswiki#4]
[JVN#67001206：『FreeStyleWiki』にクロスサイト・スクリプティングを含む複数の脆弱性](https://web.archive.org/web/20100813153626/https://www.ipa.go.jp/security/vuln/documents/2005/JVN_67001206_FreeStyleWiki.html)

**Comment by Hiroyuki-Nagata** [comment]
[Plack::Middleware::CSRFBlock - Block CSRF Attacks with minimal changes to your app](http://search.cpan.org/~mattp/Plack-Middleware-CSRFBlock-0.06/README.pod)

CSRFを防ぐ処理がPlackの側で提供されている感じ、これで対応できるか

**Comment by hangingman** [comment]
使用するにはsetup.datに適当なUUID文字列などをいれておく必要あり
例
```
# HMACSHA1を使用してセッションデータに署名するためのサーバー側シークレット
# uuidgenコマンドで作るといい感じにランダム文字列が作れるのでおすすめ
secret = 5624a9fd-d871-444f-bc17-45171d4872b2
```
